### ISSUE TITLE
Eu, como usuário, desejo efetuar meu cadastro

### ISSUE THREAD

**Issue by caloni** [AlexandreSCorreia/goiaba-alexandre-solano-correia#1]
# Eu, como usuário, desejo efetuar meu cadastro

Este ticket tem como objetivo criar uma API que permita o usuário fazer seu cadastro no sistema.

## Especificação

 - A entidade deve conter os seguintes campos: id (string), firstName (string), surname (string), age (int), creationDate (DateTime).

 - Todos os campos são obrigatórios, exceto o campo surname.

 - O campo id não deve ser inserido pelo usuário, mas gerado pelo sistema.

 - O campo creationDate não deve ser inserido pelo usuário, mas preenchido pelo sistema.

## Requisitos

 - Aplicação deve ser desenvolvida em ASP.NET Core MVC.

 - Dados devem ser persistidos para um banco de dados utilizando Entity Framework (EF Core).

 - Aplicação e banco de dados devem rodar dentro de contêineres Docker com imagem Linux (utilizar docker-compose para subir o ambiente).

 - Registra as operações (criação, deleção, edição etc) em log.

 - O projeto deve conter Testes unitários para cada operação.

## Requisitos técnicos

Consultar usuários:

### GET /Users

Resposta: 

    [
      { name: 'Cliente 1', surname: 'Sobrenome', age: 25, creationDate: '2020-12-01T01:00:00, id: 'b4f5a-b4f5a-b4f5a-b4f5a-b4f5a' '  },
      { name: 'Cliente 2', surname: 'Sobrenome 2', age: 25, creationDate: '2020-12-01T01:00:00, id: 'b4f5a-b4f5a-b4f5a-b4f5a-b4f5a' '  },
      { name: 'Cliente 3', surname: 'Sobrenome 3', age: 25, creationDate: '2020-12-01T01:00:00, id: 'b4f5a-b4f5a-b4f5a-b4f5a-b4f5a' '  }
    ]

### PUT /Users/{id}

Request:

    {
      name: 'Novo nome',
      surname: 'novo sobrenome',
      age: 26
    }

### POST /Users

    Request:
    
    {
       name: 'Nome',
       surname : 'sobrenome',
       age: 25
    }

## Documentação

 - https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-5.0
 - https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-5.0
 - https://docs.microsoft.com/en-us/dotnet/core/testing/unit-testing-with-dotnet-test

## Para aprendizado

 - https://docs.microsoft.com/pt-br/learn/modules/build-web-api-aspnet-core/
 - https://channel9.msdn.com/Series/Beginners-Series-to-Web-APIs
 - https://www.youtube.com/watch?v=mUAZ-EbGBOg

**Comment by Caloni** [comment]
O vídeo de apresentação da primeira sprint foi entregue https://www.youtube.com/watch?v=GT0X9WmkTys. É bem extenso e com vários detalhes sobre o código e a implementação. O formato ficou muito bom, cobrindo código, comportamento e caso de uso. Foi demonstrado conhecimento completo sobre a solução.

Detalhe para a criação de um volume para não perder os dados do sistema no docker:

![image](https://user-images.githubusercontent.com/1781362/186948216-1d14ca5a-fb17-4af7-b84c-d0fef65a809f.png)

Ele resolveu o problema da dependência do banco de pé usando a opção de restart aways nos containers.

![image](https://user-images.githubusercontent.com/1781362/186948249-16e2541d-e66b-47f7-98b8-fd90636f7ef6.png)

Projetos API e teste unitário extremamente bem organizados. Foi entendida a questão de mock do banco para os testes e feito em memória, além de vários cenários do que pode dar errado ter sido coberto com descrições explícitas do problema.

![image](https://user-images.githubusercontent.com/1781362/186948279-8821ddfa-2673-430c-8dc5-49fc54b684af.png)

No teste funcional é possível ver que a solução foi bem testada antes. Não houve surpresas.

![image](https://user-images.githubusercontent.com/1781362/186948313-edd48550-e9ab-4ae2-a927-8515205602bb.png)

A apresentação dos logs teve o capricho de demonstrar todo o fluxo sendo logado, incluindo as informações passadas para a operação.
