### ISSUE TITLE
Eu, como usuário do Mobile, desejo efetuar meu cadastro

### ISSUE THREAD

**Issue by caloni** [AlexandreSCorreia/goiaba-alexandre-solano-correia#2]
# Eu, como usuário do Mobile, desejo efetuar meu cadastro

## Escopo

 - Expor o CRUD de usuários via Api REST.
 - Criar um aplicativo Mobile que permita ao usuário se cadastrar.

## Requisitos técnicos

 - Aplicação deve ser desenvolvida em Xamarin.Forms.
 - API deve ser feita na aplicação já existente.

**Comment by MarceloHadad** [comment]
Descreva o que foi feito
ToDo: Descreva a melhoria ou correção que o sistema ganha com a conclusão dessa tarefa do ponto de vista do usuário. Use imagens para auxiliar e destacar os principais pontos. Se houver alteração em telas, adicione prints também.
Pense que não apenas o desenvolvimento vai ler esta seção, mas também o gerente de conta e o cliente.

Prove que você testou o que fez e que a modificação funcionou
ToDo: Coloque prints do sistema fazendo o que o escopo do ticket pede para fazer. Para frontend, prints de tela. Para backend, prints do Postman ou similares.

Documentação
ToDo: Descreva onde e por que foi inserida ou atualizada documentação sobre o componente e o projeto, o objetivo de cada seção e um exemplo. Adicione imagens ou snippets de código para auxiliar.
Esse passo é importante para agilizar a etapa de instalação do sistema.

Testes automatizados implementados
ToDo: Descreva aqui os novos testes automatizados e adicione um print do Test Explorer que mostre-os passando, o nome e o tempo de execução.

Roteiro de teste regressivo
ToDo: Evidencie o roteiro de teste regressivo, descrevendo o passo a passo para validação da funcionalidade que gerou as evidências da seção "Prove que você testou..." e que deverá ser feita após a instalação do sistema ou durante a correção do problema.

Vídeo de apresentação
ToDo: Adicione aqui o link para o vídeo de apresentação do resultado da tarefa. O vídeo deve descrever o objetivo da tarefa, apresentar a alteração no sistema e repassar o escopo.
Se a mudança for muito técnica ou complexa, apresente no vídeo a abordagem técnica utilizada, onde no código foi mexido e o motivo.
